name: sync

on: 
  schedule:
    - cron: "0 0 * * 1-7"             # scheduled for 00:00 every day
  workflow_dispatch:    
jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: upstream             # set the branch to merge to
          fetch-depth: 0 
      - name: Sync
        uses: zhangnew/sync-upstream@v1
        with:
          # User name - required for git commits
          # username: # optional, default is sync-upstream-bot
          # User email - required for git commits
          # useremail: # optional, default is bot@github.com
          # Upstream repository owner/name. For example, zhangnew/sync-upstream
          upstream: Vendicated/Vencord
          # Upstream branch to merge from. For example, master
          upstream-branch: main
          # Branch to merge to. For example, master
          branch: myPluginsKyrillk
          # Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT. We recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary. [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
          token: ${{ github.SYNC }}
          
